const fs = require('fs');
const path = require('path');

// Cấu trúc dự án và nội dung file
const projectStructure = {
  'package.json': `{
  "name": "my-portfolio",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "lucide-react": "^0.344.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-react": "^7.34.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "vite": "^5.2.0"
  }
}`,

  'vite.config.js': `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
})`,

  'tailwind.config.js': `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`,

  'postcss.config.js': `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,

  'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Portfolio</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,

  'nginx.conf': `server {
    listen 80;
    
    # Bật nén Gzip để web tải nhanh hơn
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Caching cho ảnh và assets tĩnh (1 năm)
    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}`,

  'Dockerfile': `# Stage 1: Build React App
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Nhận API Key từ Build Args (Optional)
ARG VITE_GEMINI_API_KEY
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]`,

  '.gitignore': `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# next.js build output
.next

# nuxt.js build output
.nuxt

# gatsby files
.cache/
# Comment in the public line in if your project uses public/ to store files
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Vite output
dist`
};

// Nội dung thư mục src
const srcFiles = {
  'main.jsx': `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,

  'index.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background-color: #0f172a;
  color: white;
}`,

  // App.jsx chứa toàn bộ code Portfolio
  'App.jsx': `import React, { useState, useEffect } from 'react';
import { 
  Mic, Video, Scissors, Play, Pause, Mail, Phone, Facebook, Linkedin, Youtube, Instagram, ChevronRight, Star, Target, Heart, AlertCircle, Menu, X, Sparkles, Wand2, Bot, Loader, Server, Cpu, Zap, Wifi, Home, Music 
} from 'lucide-react';

const App = () => {
  const [activeTab, setActiveTab] = useState('presenter');
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [aiInput, setAiInput] = useState('');
  const [aiResult, setAiResult] = useState(null);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiError, setAiError] = useState(null);

  useEffect(() => {
    const handleScroll = () => { setScrolled(window.scrollY > 50); };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id) => {
    setIsMenuOpen(false);
    const element = document.getElementById(id);
    if (element) { element.scrollIntoView({ behavior: 'smooth' }); }
  };

  const handleAiGenerate = async () => {
    if (!aiInput.trim()) return;
    setIsAiLoading(true); setAiError(null); setAiResult(null);
    
    // Lấy API Key từ biến môi trường (build arg) hoặc dùng chuỗi rỗng để test
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY || ""; 
    
    const prompt = \`Bạn là một Đạo diễn Âm thanh (Voice Director). Phân tích đoạn: "\${aiInput}". 
    Trả về: 1. Kịch Bản Đề Xuất (ngắn gọn), 2. Chỉ Đạo Diễn Xuất (Tone, Mood, Pace), 3. Lý do.\`;

    try {
      const response = await fetch(
        \`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=\${apiKey}\`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }),
        }
      );
      if (!response.ok) throw new Error('Không thể kết nối với AI Server.');
      const data = await response.json();
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (text) setAiResult(text);
      else throw new Error('Không nhận được phản hồi từ AI.');
    } catch (error) {
      setAiError("Xin lỗi, hệ thống AI đang bận hoặc thiếu API Key.");
      console.error("Gemini Error:", error);
    } finally { setIsAiLoading(false); }
  };

  const portfolioData = {
    voiceover: [
      { id: 1, title: "TVC Quảng cáo Coffee House", duration: "0:45", type: "Commercial", desc: "Giọng nam trầm, ấm, truyền cảm hứng." },
      { id: 2, title: "Review Sách: Nhà Giả Kim", duration: "5:20", type: "Podcast", desc: "Giọng kể chuyện, nhẹ nhàng, sâu lắng." },
      { id: 3, title: "Lồng tiếng nhân vật Game RPG", duration: "1:15", type: "Character", desc: "Đa dạng tông giọng, biểu cảm mạnh." },
    ],
    presenter: [
      { id: 1, title: "Host sự kiện Tech Summit 2024", type: "Event", image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800", desc: "Dẫn chương trình song ngữ Anh-Việt, phong cách chuyên nghiệp." },
      { id: 2, title: "Review Ẩm Thực Đường Phố", type: "Vlog", image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800", desc: "Phong cách năng động, hài hước, gần gũi." },
    ],
    editor: [
      { id: 1, title: "MV Ca Nhạc - Mùa Hè Xanh", type: "Music Video", image: "https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&q=80&w=800", desc: "Color grading, hiệu ứng chuyển cảnh theo nhịp." },
      { id: 2, title: "Corporate Video - Vingroup", type: "Business", image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=800", desc: "Dựng phim doanh nghiệp, motion graphics cơ bản." },
      { id: 3, title: "Highlight Reel Du Lịch", type: "Travel", image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=800", desc: "Kỹ thuật Speed ramp, sound design chi tiết." },
    ]
  };

  const techPassions = [
    { id: "homelab", icon: <Server size={32} />, title: "Home Lab & Server", desc: "Vận hành hệ thống Proxmox & TrueNAS. Quản trị ảo hóa, Docker container và lưu trữ dữ liệu tập trung.", color: "text-blue-400", bg: "bg-blue-500/10" },
    { id: "smarthome", icon: <Home size={32} />, title: "Smart Home (IoT)", desc: "Setup hệ sinh thái Home Assistant. Tự động hóa ánh sáng, rèm cửa và kịch bản ngữ cảnh thông minh.", color: "text-green-400", bg: "bg-green-500/10" },
    { id: "network", icon: <Wifi size={32} />, title: "Network Admin", desc: "Quản trị mạng nội bộ (LAN/VLAN), cấu hình Router Mikrotik/Ubiquiti, Firewall và VPN bảo mật.", color: "text-purple-400", bg: "bg-purple-500/10" },
    { id: "solar", icon: <Zap size={32} />, title: "Năng Lượng Mặt Trời", desc: "Đam mê năng lượng tái tạo. Theo dõi hiệu suất pin mặt trời và tối ưu hóa điện năng tiêu thụ.", color: "text-yellow-400", bg: "bg-yellow-500/10" },
    { id: "studio", icon: <Music size={32} />, title: "Professional Studio", desc: "Phòng thu âm chuẩn Acoustic. Trang thiết bị High-end: Microphone Neumann, Soundcard RME, Monitor Genelec.", color: "text-rose-400", bg: "bg-rose-500/10" },
    { id: "tech", icon: <Cpu size={32} />, title: "Hi-Tech Enthusiast", desc: "Luôn cập nhật xu hướng công nghệ mới nhất. Review và trải nghiệm các thiết bị kỹ thuật số.", color: "text-cyan-400", bg: "bg-cyan-500/10" }
  ];

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 font-sans selection:bg-rose-500 selection:text-white">
      <nav className={\`fixed w-full z-50 transition-all duration-300 \${scrolled ? 'bg-slate-900/95 shadow-lg backdrop-blur-sm py-4' : 'bg-transparent py-6'}\`}>
        <div className="container mx-auto px-6 flex justify-between items-center">
          <div className="text-2xl font-bold tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-rose-400 to-orange-300 cursor-pointer" onClick={() => scrollToSection('home')}>MY.PORTFOLIO</div>
          <div className="hidden md:flex space-x-6 lg:space-x-8 text-xs lg:text-sm font-medium">
            {['Về Tôi', 'Kỹ Năng', 'Sản Phẩm', 'Tech & Gear', 'AI Studio', 'Liên Hệ'].map((item) => (
              <button key={item} onClick={() => scrollToSection(item === 'Sản Phẩm' ? 'portfolio' : item === 'Về Tôi' ? 'about' : item === 'Kỹ Năng' ? 'skills' : item === 'Tech & Gear' ? 'tech-gear' : item === 'AI Studio' ? 'ai-studio' : 'contact')} className="hover:text-rose-400 transition-colors uppercase tracking-widest flex items-center gap-1">
                {item === 'AI Studio' && <Sparkles size={14} className="text-yellow-400" />}
                {item === 'Tech & Gear' && <Server size={14} className="text-blue-400" />}
                {item}
              </button>
            ))}
          </div>
          <div className="md:hidden">
            <button onClick={() => setIsMenuOpen(!isMenuOpen)} className="text-white focus:outline-none">{isMenuOpen ? <X size={28} /> : <Menu size={28} />}</button>
          </div>
        </div>
        {isMenuOpen && (
          <div className="md:hidden absolute top-full left-0 w-full bg-slate-800 border-t border-slate-700 p-4 flex flex-col space-y-4 shadow-xl">
             {['Về Tôi', 'Kỹ Năng', 'Sản Phẩm', 'Tech & Gear', 'AI Studio', 'Liên Hệ'].map((item) => (
              <button key={item} onClick={() => scrollToSection(item === 'Sản Phẩm' ? 'portfolio' : item === 'Về Tôi' ? 'about' : item === 'Kỹ Năng' ? 'skills' : item === 'Tech & Gear' ? 'tech-gear' : item === 'AI Studio' ? 'ai-studio' : 'contact')} className="text-left hover:text-rose-400 py-2 border-b border-slate-700/50">{item}</button>
            ))}
          </div>
        )}
      </nav>

      <section id="home" className="relative pt-32 pb-20 md:pt-48 md:pb-32 overflow-hidden">
        <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-rose-500/20 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-80 h-80 bg-blue-500/20 rounded-full blur-3xl"></div>
        <div className="container mx-auto px-6 flex flex-col-reverse md:flex-row items-center gap-12">
          <div className="w-full md:w-1/2 space-y-6 text-center md:text-left">
            <div className="inline-block px-4 py-1.5 rounded-full border border-rose-500/30 bg-rose-500/10 text-rose-300 text-sm font-medium tracking-wider mb-4">CREATIVE CONTENT CREATOR</div>
            <h1 className="text-4xl md:text-6xl font-bold leading-tight">Xin chào, tôi là <br /><span className="text-transparent bg-clip-text bg-gradient-to-r from-rose-400 to-orange-300">Nguyễn Văn A</span></h1>
            <p className="text-slate-400 text-lg md:text-xl max-w-lg mx-auto md:mx-0">Tôi kể chuyện thông qua <strong>Giọng nói</strong>, <strong>Hình ảnh</strong>. Đồng thời là một <strong className="text-blue-400">Tech Enthusiast</strong> với niềm đam mê bất tận về <strong>Home Lab</strong> & <strong>Smart Home</strong>.</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center md:justify-start pt-4">
              <button onClick={() => scrollToSection('portfolio')} className="px-8 py-3 bg-rose-500 hover:bg-rose-600 text-white rounded-full font-medium transition-all shadow-lg shadow-rose-500/25 flex items-center justify-center gap-2">Xem Portfolio <ChevronRight size={18} /></button>
              <button onClick={() => scrollToSection('contact')} className="px-8 py-3 bg-transparent border border-slate-600 hover:border-slate-400 hover:bg-slate-800 text-slate-200 rounded-full font-medium transition-all">Liên Hệ Ngay</button>
            </div>
          </div>
          <div className="w-full md:w-1/2 flex justify-center relative">
            <div className="relative w-64 h-64 md:w-96 md:h-96">
              <div className="absolute inset-0 border-2 border-slate-700 rounded-full animate-[spin_10s_linear_infinite]"></div>
              <div className="absolute inset-4 border border-rose-500/30 rounded-full animate-[spin_15s_linear_infinite_reverse]"></div>
              <div className="absolute inset-0 rounded-full overflow-hidden border-4 border-slate-800 shadow-2xl">
                <img src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800" alt="Portrait" className="w-full h-full object-cover"/>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="about" className="py-20 bg-slate-800/50">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold mb-4">Về Bản Thân</h2><div className="w-20 h-1 bg-rose-500 mx-auto rounded-full"></div><p className="mt-4 text-slate-400">Khám phá con người thật và giá trị tôi mang lại.</p></div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="bg-slate-900 p-6 rounded-2xl border border-slate-700/50 hover:border-rose-500/50 transition-all hover:transform hover:-translate-y-1 group">
              <div className="w-12 h-12 bg-blue-500/10 rounded-lg flex items-center justify-center text-blue-400 mb-4 group-hover:bg-blue-500 group-hover:text-white transition-colors"><Star size={24} /></div>
              <h3 className="text-xl font-bold mb-3">Sở Trường</h3>
              <ul className="space-y-2 text-slate-400 text-sm"><li className="flex items-start gap-2"><span className="text-blue-400 mt-1">•</span> Giọng đọc đa dạng, truyền cảm</li><li className="flex items-start gap-2"><span className="text-blue-400 mt-1">•</span> Tự tin trước ống kính</li><li className="flex items-start gap-2"><span className="text-blue-400 mt-1">•</span> Tư duy dựng phim kể chuyện</li></ul>
            </div>
             <div className="bg-slate-900 p-6 rounded-2xl border border-slate-700/50 hover:border-rose-500/50 transition-all hover:transform hover:-translate-y-1 group">
              <div className="w-12 h-12 bg-rose-500/10 rounded-lg flex items-center justify-center text-rose-400 mb-4 group-hover:bg-rose-500 group-hover:text-white transition-colors"><Heart size={24} /></div>
              <h3 className="text-xl font-bold mb-3">Sở Thích</h3>
              <ul className="space-y-2 text-slate-400 text-sm"><li className="flex items-start gap-2"><span className="text-rose-400 mt-1">•</span> Du lịch trải nghiệm</li><li className="flex items-start gap-2"><span className="text-rose-400 mt-1">•</span> Setup Home Lab & SmartHome</li><li className="flex items-start gap-2"><span className="text-rose-400 mt-1">•</span> Sưu tầm Microphone</li></ul>
            </div>
            <div className="bg-slate-900 p-6 rounded-2xl border border-slate-700/50 hover:border-rose-500/50 transition-all hover:transform hover:-translate-y-1 group">
              <div className="w-12 h-12 bg-green-500/10 rounded-lg flex items-center justify-center text-green-400 mb-4 group-hover:bg-green-500 group-hover:text-white transition-colors"><Target size={24} /></div>
              <h3 className="text-xl font-bold mb-3">Mục Tiêu</h3>
              <ul className="space-y-2 text-slate-400 text-sm"><li className="flex items-start gap-2"><span className="text-green-400 mt-1">•</span> Trở thành Top Voice 2025</li><li className="flex items-start gap-2"><span className="text-green-400 mt-1">•</span> Xây dựng kênh YouTube 100k Subs</li><li className="flex items-start gap-2"><span className="text-green-400 mt-1">•</span> Hợp tác với các brand quốc tế</li></ul>
            </div>
            <div className="bg-slate-900 p-6 rounded-2xl border border-slate-700/50 hover:border-rose-500/50 transition-all hover:transform hover:-translate-y-1 group">
              <div className="w-12 h-12 bg-orange-500/10 rounded-lg flex items-center justify-center text-orange-400 mb-4 group-hover:bg-orange-500 group-hover:text-white transition-colors"><AlertCircle size={24} /></div>
              <h3 className="text-xl font-bold mb-3">Góc "Thú Tội"</h3>
              <ul className="space-y-2 text-slate-400 text-sm"><li className="flex items-start gap-2"><span className="text-orange-400 mt-1">•</span> Quá cầu toàn, hay sửa đi sửa lại</li><li className="flex items-start gap-2"><span className="text-orange-400 mt-1">•</span> Hay quên ăn khi đang edit dở</li><li className="flex items-start gap-2"><span className="text-orange-400 mt-1">•</span> Mù đường dù có Google Maps</li></ul>
            </div>
          </div>
        </div>
      </section>

      <section id="portfolio" className="py-20">
        <div className="container mx-auto px-6">
          <div className="flex flex-col md:flex-row justify-between items-end mb-12">
            <div><h2 className="text-3xl md:text-5xl font-bold mb-4">Sản Phẩm Của Tôi</h2><p className="text-slate-400 max-w-lg">Những dự án tôi đã thực hiện với vai trò Voice Talent, Presenter và Video Editor.</p></div>
            <div className="flex bg-slate-800 p-1 rounded-xl mt-6 md:mt-0">
              <button onClick={() => setActiveTab('voiceover')} className={\`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-medium transition-all \${activeTab === 'voiceover' ? 'bg-rose-500 text-white shadow-lg' : 'text-slate-400 hover:text-white'}\`}><Mic size={16} /> Voice Over</button>
              <button onClick={() => setActiveTab('presenter')} className={\`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-medium transition-all \${activeTab === 'presenter' ? 'bg-rose-500 text-white shadow-lg' : 'text-slate-400 hover:text-white'}\`}><Video size={16} /> Presenter</button>
              <button onClick={() => setActiveTab('editor')} className={\`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-medium transition-all \${activeTab === 'editor' ? 'bg-rose-500 text-white shadow-lg' : 'text-slate-400 hover:text-white'}\`}><Scissors size={16} /> Editor</button>
            </div>
          </div>

          <div className="min-h-[400px]">
            {activeTab === 'voiceover' && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fadeIn">
                {portfolioData.voiceover.map((item) => (
                  <div key={item.id} className="bg-slate-800/50 rounded-2xl p-6 hover:bg-slate-800 transition-colors border border-slate-700/50">
                    <div className="flex justify-between items-start mb-4"><div><span className="text-xs font-bold text-rose-400 uppercase tracking-wider">{item.type}</span><h3 className="text-xl font-bold mt-1 text-white">{item.title}</h3></div><span className="text-xs font-mono bg-slate-900 px-2 py-1 rounded text-slate-400">{item.duration}</span></div><p className="text-slate-400 text-sm mb-6">{item.desc}</p>
                    <div className="bg-slate-900 rounded-xl p-3 flex items-center gap-4"><button className="w-10 h-10 bg-rose-500 rounded-full flex items-center justify-center text-white hover:scale-105 transition-transform flex-shrink-0"><Play size={18} fill="currentColor" /></button><div className="flex-1"><div className="h-1 bg-slate-700 rounded-full overflow-hidden"><div className="h-full w-1/3 bg-rose-500 rounded-full"></div></div></div></div>
                  </div>
                ))}
              </div>
            )}
            {activeTab === 'presenter' && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 animate-fadeIn">
                {portfolioData.presenter.map((item) => (
                  <div key={item.id} className="group relative rounded-2xl overflow-hidden cursor-pointer aspect-video bg-slate-800">
                    <img src={item.image} alt={item.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110 opacity-80 group-hover:opacity-100" />
                    <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-transparent to-transparent opacity-90"></div>
                    <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300"><div className="w-16 h-16 bg-rose-500/90 rounded-full flex items-center justify-center backdrop-blur-sm shadow-xl transform scale-75 group-hover:scale-100 transition-transform"><Play size={32} fill="currentColor" className="ml-1" /></div></div>
                    <div className="absolute bottom-0 left-0 p-6 w-full"><span className="bg-rose-500 text-white text-xs font-bold px-2 py-1 rounded mb-2 inline-block">{item.type}</span><h3 className="text-xl font-bold text-white mb-1">{item.title}</h3><p className="text-slate-300 text-sm line-clamp-1">{item.desc}</p></div>
                  </div>
                ))}
              </div>
            )}
            {activeTab === 'editor' && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-fadeIn">
                {portfolioData.editor.map((item) => (
                  <div key={item.id} className="bg-slate-800 rounded-2xl overflow-hidden border border-slate-700/50 hover:border-rose-500/50 transition-all hover:shadow-xl hover:shadow-rose-500/10">
                    <div className="aspect-[4/3] relative overflow-hidden group"><img src={item.image} alt={item.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" /><div className="absolute top-2 right-2 bg-black/60 backdrop-blur-sm px-2 py-1 rounded text-xs font-mono">Before / After</div></div>
                    <div className="p-5"><h3 className="font-bold text-lg mb-2">{item.title}</h3><p className="text-slate-400 text-sm mb-4 h-10 overflow-hidden">{item.desc}</p><button className="w-full py-2 border border-slate-600 rounded-lg text-sm font-medium hover:bg-slate-700 transition-colors">Xem Chi Tiết Project</button></div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </section>

      <section id="tech-gear" className="py-20 bg-slate-900 relative">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-5xl font-bold mb-4">Tech & Studio Gear</h2><div className="w-24 h-1 bg-blue-500 mx-auto rounded-full"></div><p className="mt-4 text-slate-400 max-w-2xl mx-auto">Ngoài nghệ thuật, tôi là một người đam mê công nghệ. Đây là "đồ chơi" trong <strong>Home Lab</strong> và <strong>Studio</strong> của tôi.</p></div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {techPassions.map((tech) => (
              <div key={tech.id} className="bg-slate-800/50 p-8 rounded-2xl border border-slate-700 hover:border-blue-500/50 transition-all group hover:bg-slate-800">
                <div className={\`w-14 h-14 \${tech.bg} rounded-xl flex items-center justify-center \${tech.color} mb-6 group-hover:scale-110 transition-transform\`}>{tech.icon}</div>
                <h3 className="text-xl font-bold mb-3 text-slate-100">{tech.title}</h3><p className="text-slate-400 text-sm leading-relaxed">{tech.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="skills" className="py-12 bg-rose-500 text-white overflow-hidden">
        <div className="container mx-auto px-6 mb-4 text-center"><h3 className="font-bold text-xl uppercase tracking-widest opacity-80">Bộ Công Cụ Sáng Tạo</h3></div>
        <div className="flex gap-12 justify-center flex-wrap opacity-90 text-lg font-bold"><span>Adobe Premiere</span><span>•</span><span>Audition</span><span>•</span><span>Davinci Resolve</span><span>•</span><span>After Effects</span><span>•</span><span>Proxmox VE</span><span>•</span><span>Home Assistant</span><span>•</span><span>TrueNAS Scale</span><span>•</span><span>Docker</span></div>
      </section>

      <section id="ai-studio" className="py-20 bg-gradient-to-br from-indigo-900 to-slate-900 relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none"><div className="absolute top-10 left-10 w-32 h-32 bg-purple-500/20 rounded-full blur-3xl animate-pulse"></div><div className="absolute bottom-10 right-10 w-64 h-64 bg-rose-500/10 rounded-full blur-3xl"></div></div>
        <div className="container mx-auto px-6 relative z-10">
          <div className="text-center mb-12"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-800 border border-purple-500/50 text-purple-300 text-sm font-bold mb-4"><Sparkles size={16} /> POWERED BY GEMINI AI</div><h2 className="text-3xl md:text-5xl font-bold mb-4 text-white">Trợ Lý Kịch Bản AI ✨</h2><p className="text-slate-400 max-w-2xl mx-auto">Trải nghiệm công nghệ AI để tối ưu hóa kịch bản và nhận chỉ đạo diễn xuất (Voice Direction) ngay lập tức. Nhập ý tưởng thô của bạn, tôi sẽ giúp bạn biến nó thành tác phẩm.</p></div>
          <div className="max-w-4xl mx-auto bg-slate-800/80 backdrop-blur-md rounded-2xl border border-slate-700 shadow-2xl overflow-hidden flex flex-col md:flex-row">
            <div className="w-full md:w-1/2 p-6 md:p-8 border-b md:border-b-0 md:border-r border-slate-700 flex flex-col">
              <div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 bg-slate-700 rounded-lg flex items-center justify-center text-rose-400"><Bot size={24} /></div><h3 className="font-bold text-lg">Nhập Ý Tưởng / Kịch Bản Thô</h3></div>
              <textarea className="flex-1 w-full bg-slate-900/50 border border-slate-600 rounded-xl p-4 text-slate-200 focus:outline-none focus:border-rose-500 focus:ring-1 focus:ring-rose-500 transition-all resize-none mb-4 min-h-[200px]" placeholder="Ví dụ: Tôi muốn làm một video giới thiệu về quán cà phê phong cách vintage, nhạc nhẹ nhàng, hướng tới giới trẻ..." value={aiInput} onChange={(e) => setAiInput(e.target.value)}></textarea>
              <button onClick={handleAiGenerate} disabled={isAiLoading || !aiInput.trim()} className="w-full py-3 bg-gradient-to-r from-rose-500 to-purple-600 hover:from-rose-600 hover:to-purple-700 text-white font-bold rounded-xl transition-all shadow-lg shadow-rose-500/20 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed group">{isAiLoading ? (<><Loader size={20} className="animate-spin" /> Đang Phân Tích...</>) : (<><Wand2 size={20} className="group-hover:rotate-12 transition-transform" /> ✨ Phân Tích & Tối Ưu</>)}</button>
            </div>
            <div className="w-full md:w-1/2 p-6 md:p-8 bg-slate-900/50 flex flex-col">
               <div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 bg-slate-700 rounded-lg flex items-center justify-center text-green-400"><Sparkles size={24} /></div><h3 className="font-bold text-lg">Kết Quả Phân Tích</h3></div>
              <div className="flex-1 bg-slate-800/50 rounded-xl border border-slate-700 p-4 overflow-y-auto max-h-[400px]">
                {aiError && (<div className="text-rose-400 flex items-center gap-2"><AlertCircle size={18} /> {aiError}</div>)}
                {!aiResult && !isAiLoading && !aiError && (<div className="h-full flex flex-col items-center justify-center text-slate-500 text-center opacity-60"><Bot size={48} className="mb-4" /><p>Kết quả sẽ hiển thị tại đây...</p></div>)}
                {isAiLoading && (<div className="space-y-4 animate-pulse"><div className="h-4 bg-slate-700 rounded w-3/4"></div><div className="h-4 bg-slate-700 rounded w-full"></div><div className="h-4 bg-slate-700 rounded w-5/6"></div><div className="h-20 bg-slate-700 rounded w-full mt-4"></div></div>)}
                {aiResult && (<div className="prose prose-invert prose-sm max-w-none whitespace-pre-line text-slate-300">{aiResult}</div>)}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="contact" className="py-20 relative">
        <div className="container mx-auto px-6 max-w-4xl">
          <div className="bg-slate-800 rounded-3xl p-8 md:p-12 border border-slate-700 shadow-2xl">
            <div className="text-center mb-10"><h2 className="text-3xl font-bold mb-4">Sẵn Sàng Hợp Tác?</h2><p className="text-slate-400">Hãy để lại lời nhắn nếu bạn đang tìm kiếm một giọng đọc, một MC hay một editor cho dự án sắp tới.</p></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
              <div className="space-y-6">
                <div className="flex items-center gap-4"><div className="w-12 h-12 bg-slate-900 rounded-full flex items-center justify-center text-rose-500"><Mail size={20} /></div><div><p className="text-sm text-slate-400">Email</p><p className="font-medium">contact@yourname.com</p></div></div>
                <div className="flex items-center gap-4"><div className="w-12 h-12 bg-slate-900 rounded-full flex items-center justify-center text-rose-500"><Phone size={20} /></div><div><p className="text-sm text-slate-400">Hotline / Zalo</p><p className="font-medium">0909 123 456</p></div></div>
                <div className="pt-6"><p className="text-sm text-slate-400 mb-4">Mạng Xã Hội</p><div className="flex gap-4"><a href="#" className="w-10 h-10 bg-slate-700 rounded-full flex items-center justify-center hover:bg-rose-500 hover:text-white transition-all"><Facebook size={18} /></a><a href="#" className="w-10 h-10 bg-slate-700 rounded-full flex items-center justify-center hover:bg-rose-500 hover:text-white transition-all"><Linkedin size={18} /></a><a href="#" className="w-10 h-10 bg-slate-700 rounded-full flex items-center justify-center hover:bg-rose-500 hover:text-white transition-all"><Youtube size={18} /></a><a href="#" className="w-10 h-10 bg-slate-700 rounded-full flex items-center justify-center hover:bg-rose-500 hover:text-white transition-all"><Instagram size={18} /></a></div></div>
              </div>
              <form className="space-y-4">
                <div><input type="text" placeholder="Tên của bạn" className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 focus:outline-none focus:border-rose-500 transition-colors text-white" /></div>
                <div><input type="email" placeholder="Email liên hệ" className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 focus:outline-none focus:border-rose-500 transition-colors text-white" /></div>
                <div><textarea rows="4" placeholder="Nội dung công việc..." className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 focus:outline-none focus:border-rose-500 transition-colors text-white"></textarea></div>
                <button type="button" className="w-full bg-gradient-to-r from-rose-500 to-orange-400 text-white font-bold py-3 rounded-lg hover:opacity-90 transition-opacity">Gửi Tin Nhắn</button>
              </form>
            </div>
          </div>
        </div>
      </section>

      <footer className="py-8 bg-slate-900 border-t border-slate-800 text-center text-slate-500 text-sm"><p>© 2024 Your Name Portfolio. All rights reserved.</p></footer>

      <style>{\`@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } } .animate-fadeIn { animation: fadeIn 0.5s ease-out forwards; }\`}</style>
    </div>
  );
};

export default App;`
};

// Hàm tạo thư mục và file
const createProject = () => {
  console.log("🚀 Đang khởi tạo dự án Portfolio...");

  // Tạo file gốc
  for (const [fileName, content] of Object.entries(projectStructure)) {
    fs.writeFileSync(fileName, content);
    console.log(\`✅ Đã tạo: \${fileName}\`);
  }

  // Tạo thư mục src
  const srcDir = path.join(__dirname, 'src');
  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir);
    console.log("📂 Đã tạo thư mục: src");
  }

  // Tạo file trong src
  for (const [fileName, content] of Object.entries(srcFiles)) {
    fs.writeFileSync(path.join(srcDir, fileName), content);
    console.log(\`✅ Đã tạo: src/\${fileName}\`);
  }

  console.log("\\n🎉 Xong! Giờ hãy chạy lệnh sau để bắt đầu:");
  console.log("👉 npm install");
  console.log("👉 npm run dev");
};

createProject();